### ISSUE TITLE
URL 报错

### ISSUE THREAD

**Issue by thbgh** [lichaozhy/cas-client#1]
![image](https://user-images.githubusercontent.com/9399517/68113072-da254e80-ff2d-11e9-9284-1543db4a66e4.png)
大兄弟,你自己用得怎么样? 我用你的有这个报错.

**Comment by lichaozhy** [comment]
https://nodejs.org/dist/latest-v13.x/docs/api/url.html#url_the_whatwg_url_api


Version | Changes
-- | --
v10.0.0 | The class is now available on the global object.
v7.0.0, v6.13.0 | Added in: v7.0.0, v6.13.0

**Comment by thbgh** [comment]
ok,
thanks
